title: National Robotics Programme
url: "https://nrp.gov.sg" # the base hostname & protocol for your site, e.g. http://example.com
favicon: /images/favicon-nrp.ico
description: The National Robotics Programme of Singapore

# Site colors
colors:
  primary-color: '#363a3c'
  secondary-color: '#d6231d'
  media-colors:
    - title: media-color-one
      color: '#49759a'
    - title: media-color-two
      color: '#4b5459'
    - title: media-color-three
      color: '#8f0000'
    - title: media-color-four
      color: '#004e91'
    - title: media-color-five
      color: '#009144'


collections:
  who-we-are:
    output: true
  research:
    output: true
  industry:
    output: true
  engineering:
    output: true
  careers:
    output: true
  events:
    output: true
  archives:
    output: true
  community:
    output: true
resources_name: news-media

##################################################################################################################
# Everything below this line is Isomer-specific configuration. There should not be a need to edit these settings #
##################################################################################################################
permalink: none
baseurl: ""
exclude: [travis-script.js, .travis.yml, README.md, package.json, package-lock.json, node_modules, vendor/bundle/, vendor/cache/, vendor/gems/, vendor/ruby/, Gemfile, Gemfile.lock]
include: [_redirects]
defaults:
  - scope:
      path: ""
    values:
      layout: "page"
# Custom CSS file path
custom_css_path: "/misc/custom.css"
custom_print_css_path: "/assets/css/print.css"
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
