- title: Autonomous Environmental Service Vehicles for Singapore
  date: 14 Jul 2021
  desc: 
  img: /images/placeholder.jpg

- title: "Toucan: A New Class of Versatile Robots for Pest Control and Drain Inspection Tasks"
  date: 31 Oct 2021
  desc: 
  img: /images/placeholder.jpg

- title: "Panthera: A Self-reconfigurable Class of Pavement Sweeping Robot"
  date: 30 Apr 2023
  desc: 
  img: /images/placeholder.jpg