- title: Autonomous Environmental Service Vehicles for Singapore
  date: 14 Jul 2021
  desc: Service Vehicles that could autonomously navigate through designated areas and clean them, with less consrains on manpower and timing. Autonomy and eventual assessment of cleanliness
  img: /images/placeholder.jpg

- title: "Toucan: A New Class of Versatile Robots for Pest Control and Drain Inspection Tasks"
  date: 31 Oct 2021
  desc: Small robots that could fit into false ceilings and other facades to inspect for pests and other anomalies.
  img: /images/placeholder.jpg

- title: "Development of automated system for the mass production and deployment of male Wolbachia-Aedes mosquitoes"
  date: 31 Oct 2021
  desc: Automated system that could rear male Aedes mosquitoes modified with the Wolbalchia bacterium, thereby control the mosquito population and reducing the likelihood of dengue outbreaks.
  img: /images/placeholder.jpg

- title: "Panthera: A Self-reconfigurable Class of Pavement Sweeping Robot"
  date: 30 Apr 2023
  desc: A pavement sweeping robot that could autonomously clean the assigned pavement, and adjust its width according to the pavement conditions and presence of crowds.
  img: /images/placeholder.jpg